spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/zvon73
    username: postgres
    password: azor1234
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mail.ru
    port: 465
    username: "zvon-73@mail.ru"
    password: "8txkKuqvPA9r6LrWzFN8"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

jwt:
  secret: "62A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855"
  expiration: 3600000
server:
  port: 8080